// <auto-generated />
using System;
using CareHomeLeaveManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareHomeLeaveManagement.Infrastructure.Migrations
{
    [DbContext(typeof(CareHomeLeaveManagementDbContext))]
    [Migration("20260922060434_AddHoursTakenToLeaveRequest")]
    partial class AddHoursTakenToLeaveRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxConcurrentLeave")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Carer",
                            MaxConcurrentLeave = 2
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Domestic Worker",
                            MaxConcurrentLeave = 1
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Nurse",
                            MaxConcurrentLeave = 1
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Kitchen Staff",
                            MaxConcurrentLeave = 1
                        });
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<decimal>("WeeklyHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.Entitlement", b =>
                {
                    b.Property<int>("EntitlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntitlementId"));

                    b.Property<decimal>("AllocatedHrs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TakenHrs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EntitlementId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FiscalYearId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("Entitlements");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.EntitlementHistory", b =>
                {
                    b.Property<int>("EntitlementHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntitlementHistoryId"));

                    b.Property<int>("EntitlementId")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NewAllocationHrs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewTakenHrs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldAllocationHrs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldTakenHrs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("EntitlementHistoryId");

                    b.HasIndex("EntitlementId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("EntitlementHistories");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.FiscalYear", b =>
                {
                    b.Property<int>("FiscalYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FiscalYearId"));

                    b.Property<int?>("GeneratedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeneratedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("FiscalYearId");

                    b.HasIndex("GeneratedBy");

                    b.ToTable("FiscalYears");

                    b.HasData(
                        new
                        {
                            FiscalYearId = 1,
                            Year = "2026-2027"
                        },
                        new
                        {
                            FiscalYearId = 2,
                            Year = "2027-2028"
                        },
                        new
                        {
                            FiscalYearId = 3,
                            Year = "2028-2029"
                        },
                        new
                        {
                            FiscalYearId = 4,
                            Year = "2029-2030"
                        },
                        new
                        {
                            FiscalYearId = 5,
                            Year = "2030-2031"
                        });
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.LeaveHistory", b =>
                {
                    b.Property<int>("LeaveHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveHistoryId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NewEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NewStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OldEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OldStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("LeaveHistoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LeaveRequestId");

                    b.ToTable("LeaveHistories");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveRequestId"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HoursTaken")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerComment")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("LeaveRequestId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiresEntitlement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("LeaveTypeId");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            LeaveTypeId = 1,
                            Name = "Annual Leave",
                            RequiresEntitlement = true
                        },
                        new
                        {
                            LeaveTypeId = 2,
                            Name = "Birthday Leave",
                            RequiresEntitlement = false
                        });
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("LoginId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.Employee", b =>
                {
                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.Employee", "Manager")
                        .WithMany("TeamMembers")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.Entitlement", b =>
                {
                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.FiscalYear", "FiscalYear")
                        .WithMany()
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("FiscalYear");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.EntitlementHistory", b =>
                {
                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.Entitlement", "Entitlement")
                        .WithMany()
                        .HasForeignKey("EntitlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.Employee", "ModifiedByEmployee")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entitlement");

                    b.Navigation("ModifiedByEmployee");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.FiscalYear", b =>
                {
                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.Employee", "GeneratedByEmployee")
                        .WithMany()
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GeneratedByEmployee");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.LeaveHistory", b =>
                {
                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.LeaveRequest", "LeaveRequest")
                        .WithMany("LeaveHistory")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LeaveRequest");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.Employee", "Approver")
                        .WithMany("ApprovedLeaveRequests")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.LeaveType", "LeaveType")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.Login", b =>
                {
                    b.HasOne("CareHomeLeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithOne("Login")
                        .HasForeignKey("CareHomeLeaveManagement.Domain.Entities.Login", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.Employee", b =>
                {
                    b.Navigation("ApprovedLeaveRequests");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Login");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.LeaveRequest", b =>
                {
                    b.Navigation("LeaveHistory");
                });

            modelBuilder.Entity("CareHomeLeaveManagement.Domain.Entities.LeaveType", b =>
                {
                    b.Navigation("LeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
